### PR TITLE
Hunter pet enhancements

### PR DESCRIPTION
**Pull request by SamKacer**
At a high level makes changes to overview and announcement of pet happiness

### Overview changes
- pet health displayed below player mana in general section
- pet section presented at bottom to hunters, containing:
    - pet experience progress
    - loyalty
    - available training points
    - happiness

### Pet happiness announcements changes
- not announced when player is dead
- announce ASAP if has increased
- announce once a minute when not happy

commit messages:
- Add pet health to overview
- Add loyalty and TP to pet section
- Add happiness and loyalty gain rate to pet section
- Speak when pet happiness has increased from feeding
- Fix pet training points
- Check if player dead and pet exists for pet happiness announcements
- Simplify speak pet happiness condition
- Remove loyalty rate from pet section
- Reuse pet happiness string
- Show pet section only to hunters
- Small fixes
- Add english "training points"

### CODE REVIEW

**Comment by SamKacer** [comment]
One thing to note, is that although the intention is that the script checks every 2 second whether happiness has increased, in reality there tends to be a longer delay before the new happiness is announced after feeding, about 5-10 seconds usually. Not sure if this is because in the game it takes a little while for the happiness to increase after feeding or whether it is because of the loop not being executed often enough.

**Comment by Duugu** [comment]
Thanks a lot.
On thing: please try to avoid global functions like SkuCorePlayerIsHunter.
I would suggest to either make them local, or add them to the modul table if you would like to use them from other modules.

**Comment by Duugu** [comment]
> 

I am unsure what you mean. :)
2 seconds?

**Comment by SamKacer** [comment]
> Thanks a lot. On thing: please try to avoid global functions like SkuCorePlayerIsHunter. I would suggest to either make them local, or add them to the modul table if you would like to use them from other modules.


ok, no problem. Didn't add it to the module table since it already started with SkuCore, so figured chance of a name clash was low. I will change it so it is in module table when I get home

**Comment by SamKacer** [comment]
Oh, wait, didn't notice it was already merged lol

Will keep the globals thing in mind for the future :)

Also forgot to mention that thing left to implement was the german translation for "training points". You likely noticed it, but just in case ;)

**Pull request merged**
