### PR TITLE
Fix gun/crossbow comparisn and exclude bank from all bags

### PR DESCRIPTION
**Pull request by SamKacer**
### changes
- fix guns and crossbows not showing currently equipped item
- fix bank items showing up in "all bags"

### Notes

I also extracted out 2 regions of duplicated code. I did that because I was looking into adding item comparisn for quest rewards. I didn't end up figuring out how to enhance quest rewards, but I think this refactoring is small and of value regardless, so I decided to include it here.

### commit messages:
- Compare equip for guns/crossbows
- Only show bag items in all bags menu
- Extract out insertComparisnSections function

### CODE REVIEW

**Comment by SamKacer** [comment]
So, I tested my change for showing item comparisn for quest rewards. I've been playing with it for a couple of hours and completed 5 or 6 quests and everything seems to be working fine. Only concern I have is that I haven't had a quest where the quest reward is pre-determined, i.e. you don't choose. I am guessing worst case though, it just won't show the comparisn for those sort of rewards, but that wouldn't be a huge deal anyway, since comparing current eq in such a scenario isn't important since you can just do it in your bag right after.

So I just also pushed that change as well. As part of this PR

**Comment by SamKacer** [comment]
Ok, I just got a quest with "receive" quest rewards instead of "choose" rewards and was able to implement comparisns for those types of rewards as well. So now it should cover all types of rewards

**Comment by Duugu** [comment]
Hey. Did you test that with new reward types like skills, talent points, compagnions, etc. too?

**Comment by SamKacer** [comment]
@Duugu hey good point! I have actually not come across these yet... What is the easiest way to access such quests? Are such quests only inn the DK starting area right now?

**Comment by SamKacer** [comment]
Doing some thought experiments and trying out some code snippets (such as the case if itemLink = nil), I think it will probably work correctly. But if I could find some of these quests then I could also confirm

**Pull request merged**
